'use client';

import React, { useEffect, useRef, useCallback } from 'react';
import { db } from '@/lib/firebase';
import { doc, getDoc, setDoc, collection, addDoc, query, where, getDocs } from 'firebase/firestore';
import { generateContentFromMaster } from '@/lib/automation';

/**
 * SONAI - Automation Engine
 * This components runs in the background when the admin is active.
 */
export function AutomationEngine() {
  const lastRunRef = useRef<string | null>(null);

  const executeAutomationFlow = useCallback(async (slot: string, settings: any) => {
    try {
      // 1. Log Run Start
      await addDoc(collection(db, 'logs'), {
        runAt: new Date().toISOString(),
        status: 'pending',
        message: `SONAI Sequential Cycle [${slot}] Initiated`
      });

      // 2. Find all Active Intelligence Nodes (Multi-Page Support)
      const q = query(collection(db, 'masterPrompts'), where('isActive', '==', true));
      const promptSnap = await getDocs(q);
      
      if (promptSnap.empty) {
        throw new Error('No Intelligence Nodes active or linked.');
      }

      // 3. Process every node in sequence
      for (const promptDoc of promptSnap.docs) {
        const masterPrompt = promptDoc.data();
        
        // Skip if no page is linked
        if (!masterPrompt.linkedPageId) {
          console.warn(`Node [${masterPrompt.brandName}] skipped: No Target Page Link.`);
          continue;
        }

        // Generate Content (Alternate between image and video)
        const mediaPref = Math.random() > 0.5 ? 'image' : 'video';
        const content = await generateContentFromMaster({
          ...masterPrompt,
          mediaPreference: mediaPref
        });

        // Save Content with target Page ID
        const contentRef = await addDoc(collection(db, 'contents'), {
          ...content,
          targetPageId: masterPrompt.linkedPageId,
          brandName: masterPrompt.brandName,
          status: settings.manualApproval ? 'ready' : 'posted',
          createdAt: new Date().toISOString(),
          promptSource: promptDoc.id,
          isAutoGenerated: true
        });

        // Individual Success Log per node
        await addDoc(collection(db, 'logs'), {
          runAt: new Date().toISOString(),
          status: 'success',
          message: `Node [${masterPrompt.brandName}] auto-posted to Page [${masterPrompt.linkedPageId}].`,
          contentId: contentRef.id
        });
      }

      // 4. Update Global Global Heartbeat
      await setDoc(doc(db, 'settings', 'global'), {
        lastRunAt: new Date().toLocaleTimeString(),
        updatedAt: new Date().toISOString()
      }, { merge: true });

    } catch (e: any) {
      await addDoc(collection(db, 'logs'), {
        runAt: new Date().toISOString(),
        status: 'failed',
        message: `Automation Node Failure: ${e.message}`
      });
    }
  }, []);

  const checkAndRunAutomation = useCallback(async () => {
    try {
      const settingsSnap = await getDoc(doc(db, 'settings', 'global'));
      let isAutomationEnabled = true;
      if (settingsSnap.exists()) {
        isAutomationEnabled = settingsSnap.data().isAutomationEnabled !== false;
      }
      
      if (!isAutomationEnabled) return;

      const now = new Date();
      const currentHour = now.getHours();
      const currentMinute = now.getMinutes();
      
      // Execute every 2 hours (0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22)
      // Only trigger in the first 5 minutes of the hour
      if (currentHour % 2 === 0 && currentMinute < 5) {
        const timeSlot = `${now.toDateString()} ${currentHour}`;
        if (lastRunRef.current !== timeSlot) {
          lastRunRef.current = timeSlot;
          await executeAutomationFlow(`Cycle ${currentHour}:00`, { manualApproval: false });
        }
      }
    } catch (e) {
      console.error('Automation Engine Error:', e);
    }
  }, [executeAutomationFlow]);

  useEffect(() => {
    const interval = setInterval(() => {
      checkAndRunAutomation();
    }, 60000);

    return () => clearInterval(interval);
  }, [checkAndRunAutomation]);

  return null; // Invisible core engine
}
