'use client';

import React, { useEffect, useRef, useCallback } from 'react';
import { db } from '@/lib/firebase';
import { doc, getDoc, setDoc, collection, addDoc, query, where, getDocs } from 'firebase/firestore';
import { generateContentFromMaster } from '@/lib/automation';

/**
 * SONAI - Automation Engine
 * This components runs in the background when the admin is active.
 */
export function AutomationEngine() {
  const lastRunRef = useRef<string | null>(null);

  const executeAutomationFlow = useCallback(async (slot: string, settings: any) => {
    try {
      // 1. Log Run Start
      await addDoc(collection(db, 'logs'), {
        runAt: new Date().toISOString(),
        status: 'pending',
        message: `SONAI Cycle [${slot}] Initiated`
      });

      // 2. Find Master Prompt
      const q = query(collection(db, 'masterPrompts'), where('isActive', '==', true));
      const promptSnap = await getDocs(q);
      if (promptSnap.empty) throw new Error('SONAI Intelligence core not active.');
      
      const masterPrompt = promptSnap.docs[0].data();

      // 3. Generate Content (Cycle between image/video for variety)
      const mediaPref = Math.random() > 0.5 ? 'image' : 'video';
      const content = await generateContentFromMaster({
        ...masterPrompt,
        mediaPreference: mediaPref
      });

      // 4. Save Content
      const contentRef = await addDoc(collection(db, 'contents'), {
        ...content,
        mediaType: mediaPref,
        status: settings.manualApproval ? 'ready' : 'posted',
        createdAt: new Date().toISOString(),
        promptSource: promptSnap.docs[0].id,
        isAutoGenerated: true
      });

      // 5. Update Global Stats
      await setDoc(doc(db, 'settings', 'global'), {
        lastRunAt: new Date().toLocaleTimeString(),
        updatedAt: new Date().toISOString()
      }, { merge: true });

      // 6. Log Success
      await addDoc(collection(db, 'logs'), {
        runAt: new Date().toISOString(),
        status: 'success',
        message: `Content generated successfully for ${slot}. Status: ${settings.manualApproval ? 'Manual Approval Required' : 'Auto-Scheduled'}`,
        contentId: contentRef.id
      });

    } catch (e: any) {
      await addDoc(collection(db, 'logs'), {
        runAt: new Date().toISOString(),
        status: 'failed',
        message: `Automation failed: ${e.message}`
      });
    }
  }, []);

  const checkAndRunAutomation = useCallback(async () => {
    try {
      const settingsSnap = await getDoc(doc(db, 'settings', 'global'));
      if (!settingsSnap.exists() || !settingsSnap.data().isAutomationEnabled) return;
      const settings = settingsSnap.data();

      const now = new Date();
      const currentHour = now.getHours();
      const currentMinute = now.getMinutes();
      const ampm = currentHour >= 12 ? 'PM' : 'AM';
      const displayHour = currentHour % 12 || 12;
      const timeSlot = `${displayHour} ${ampm}`;

      const scheduleSnap = await getDoc(doc(db, 'schedule', 'default'));
      if (!scheduleSnap.exists()) return;
      const schedule = scheduleSnap.data();

      if (schedule[timeSlot] && currentMinute < 2 && lastRunRef.current !== timeSlot) {
        lastRunRef.current = timeSlot;
        await executeAutomationFlow(timeSlot, settings);
      }
    } catch (e) {
      console.error('Automation Engine Error:', e);
    }
  }, [executeAutomationFlow]);

  useEffect(() => {
    const interval = setInterval(() => {
      checkAndRunAutomation();
    }, 60000);

    return () => clearInterval(interval);
  }, [checkAndRunAutomation]);

  return null; // Invisible core engine
}
